### ISSUE TITLE
follow_joint_trajectory does not return feedback messages  (ros ticket #5158)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_controllers#357]
When using executing a trajectory in the warehouse viewer, the follow_joint_trajectory action does not give feedback:
"rostopic echo /r_arm_controller/follow_joint_trajectory/feedback" will not show any messages.  The follow_joint_trajectory/goal and follow_joint_action/result messages are OK.

This probably affects at least the following: r_arm_controller, l_arm_controller, follow_joint_trajectory, and joint_trajectory_action.

I will attempt to workaround this by subscribing to /r_arm_controller/state instead.  They have similar structure.  However, using the feedback message would be preferred in the long run.

trac data:
- Owner: **sglaser**
- Reporter: **kanderson**
- Reported at: **Tue Nov  1 09:53:14 2011**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/5158

**Comment by furushchev** [comment]
I have the same problem.
Is there any proceeding?

**Comment by ahendrix** [comment]
This ticket is over two years old; I don't think anyone is working on it.

I'm willing to accept a pull request if you come up with a solution.

The root of the problem here is that the JointTrajectoryAction in pr2_controllers_msgs doesn't define any feedback or result data. If you want to try to fix this, I would start by adding a second action type that defines the feedback and result data you're looking for, and then extend the joint_trajectory_action controller to use the new action type in addition to the old action type.

**Comment by furushchev** [comment]
The rosmsg of topic /controller_name/joint_trajectory_action is pr2_controllers_msgs/JointTrajectoryAction, which is no feedback and result, I understand. But PR2 also publishes /controller_name/follow_joint_trajectory that has rosmsg type of control_msgs/FollowJointTrajectory, which has both feedback and result, but it doesn't just publish them.
Is it means that when using follow_joint_trajectory we can move the pr2 actuators but cannot get feedback data because of not impremented program?

**Comment by ahendrix** [comment]
Fixed in #371
